//! Regex patterns and filename classifiers used by the PR classifier.

use regex::Regex;
use std::path::Path;
use std::sync::OnceLock;

fn re(pattern: &str) -> Regex {
    Regex::new(pattern).expect("valid regex")
}

pub fn destructive_sql_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(r"(?i)\b(DROP\s+(TABLE|COLUMN|DATABASE|INDEX|VIEW|SCHEMA)|TRUNCATE\s+TABLE|DELETE\s+FROM\s+\w+\s*(;|$)|ALTER\s+TABLE\s+\w+\s+DROP)\b")
    })
}

pub fn schema_ddl_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(r"(?i)\b(CREATE\s+(TABLE|INDEX|VIEW|TYPE|FUNCTION|PROCEDURE|TRIGGER)|ALTER\s+(TABLE|COLUMN|INDEX))\b")
    })
}

pub fn auth_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(r"(?i)\b(bcrypt|scrypt|argon2|passport|jsonwebtoken|jwt\.(sign|verify|decode)|oauth2?|authorize|authenticate|getSession|setSession|cookie\.sign|csrf|csp|same-?site|sso|saml)\b")
    })
}

pub fn payment_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(r"(?i)\b(stripe|braintree|paypal|squareup|plaid|chargebee|adyen|checkout\.com|invoice|refund|charge\(|createPayment|subscription|billing|price_|line_items|webhook)\b")
    })
}

pub fn crypto_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(r"(?i)\b(createCipher|createDecipheriv|randomBytes|createHash|createHmac|pbkdf2|scrypt|ed25519|rsa|ecdsa|getRandomValues|crypto\.subtle)\b")
    })
}

pub fn removed_error_handling_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| re(r"^\s*(}\s*catch\b|except\b|rescue\b|\.catch\(|throw\s|panic!|unwrap\()"))
}

pub fn exported_symbol_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(r"^\s*(export\s+(default\s+|async\s+)?(function|class|const|let|interface|type|enum)|pub\s+(async\s+)?(fn|struct|enum|trait|type|const)|public\s+(class|interface|enum)|module\.exports\.\w+\s*=)")
    })
}

pub fn risk_keyword_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(r"(?i)\b(hotfix|emergency|bypass|hack\b|XXX|temp\s*fix|quick\s*fix|workaround|YOLO)\b")
    })
}

pub fn breaking_change_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| re(r"(?m)^(BREAKING CHANGE:|\w+(\(.+\))?!:\s)"))
}

/// Control-flow keywords used as a cheap stand-in for semantic churn density.
/// Research (Codequiry 2026) shows lines-of-code correlates poorly with
/// defects (r=0.12) while AST-level semantic churn correlates r=0.74. True
/// AST diffing is expensive; counting control-flow tokens added vs removed
/// is a fast, language-agnostic approximation.
pub fn control_flow_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(
            r"(?i)\b(if|else|for|while|switch|case|match|try|catch|except|rescue|finally|return|throw|raise|panic!|unwrap|yield|break|continue|goto|await|async|=>|\?\s*:|\|\|)\b",
        )
    })
}

/// Logging / telemetry / print calls. Removal of these is frequently a smell
/// — either the author is silencing an error they don't understand, or
/// hiding an instrumentation path. Additions of logging aren't suspicious.
pub fn logging_call_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(
            r"(?i)\b(console\.(log|info|warn|error|debug|trace)|logger\.(log|info|warn|error|debug|trace|exception)|log\.(info|warn|error|debug|trace)|print\s*\(|println!|eprintln!|dbg!|System\.out\.print|fmt\.Print|panic!|trace!|info!|warn!|error!|debug!)",
        )
    })
}

/// Lines in the diff that mark a file as auto-generated. Common markers
/// across toolchains. Matching any of these in the added lines earns the
/// file the "generated" classification, which mutes size / churn scoring.
pub fn generated_marker_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        re(
            r"(?i)(@generated\b|DO NOT EDIT|AUTO-?GENERATED|GENERATED BY|Code generated by|This file was automatically generated)",
        )
    })
}

/// Dependency manifest line in `package.json` / `Cargo.toml` /
/// `requirements.txt` style. Captures the package name and version string.
/// Used to detect major-version bumps when paired with the removed line.
pub fn dep_manifest_line_re() -> &'static Regex {
    static R: OnceLock<Regex> = OnceLock::new();
    R.get_or_init(|| {
        // JSON: "pkg": "^1.2.3" | "~1.2.3" | "1.2.3"
        // TOML: pkg = "1.2.3"
        // Requirements: pkg==1.2.3 or pkg>=1.2.3
        re(
            r#"(?i)["']?([A-Za-z0-9_\-\.@/]+)["']?\s*[:=]+\s*["']?\s*[~^><=! ]*\s*(\d+)\.(\d+)\.(\d+)"#,
        )
    })
}

/// Files that should not contribute to size / churn scoring. Complements
/// `is_lock_or_generated` with build outputs and common generated asset
/// types.
pub fn is_generated_or_binary_file(path: &str) -> bool {
    if is_lock_or_generated(path) {
        return true;
    }
    let lower = path.to_lowercase();
    let name = Path::new(&lower)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("");
    // Generated source patterns across toolchains.
    lower.contains(".generated.")
        || lower.contains(".gen.")
        || lower.ends_with(".pb.go")
        || lower.ends_with(".pb.cc")
        || lower.ends_with(".pb.h")
        || lower.ends_with("_pb2.py")
        || lower.ends_with("_pb2.pyi")
        || lower.ends_with(".g.dart")
        || lower.ends_with(".freezed.dart")
        || lower.ends_with(".d.ts") // usually generated types
        || name == "openapi.yaml"
        || name == "openapi.yml"
        || name == "openapi.json"
        || name == "swagger.yaml"
        || name == "swagger.json"
        || name.ends_with(".proto.ts")
        // Binary / asset extensions that appear in diffs as binary markers.
        || lower.ends_with(".png")
        || lower.ends_with(".jpg")
        || lower.ends_with(".jpeg")
        || lower.ends_with(".gif")
        || lower.ends_with(".webp")
        || lower.ends_with(".ico")
        || lower.ends_with(".pdf")
        || lower.ends_with(".zip")
        || lower.ends_with(".tar")
        || lower.ends_with(".gz")
        || lower.ends_with(".woff")
        || lower.ends_with(".woff2")
        || lower.ends_with(".ttf")
        || lower.ends_with(".otf")
        || lower.ends_with(".mp3")
        || lower.ends_with(".mp4")
        || lower.ends_with(".mov")
        || lower.ends_with(".wasm")
        // Common build output dirs
        || lower.contains("/dist/")
        || lower.contains("/build/")
        || lower.contains("/out/")
        || lower.starts_with("dist/")
        || lower.starts_with("build/")
        || lower.starts_with("out/")
}

// ============================================================================
// Filename classification
// ============================================================================

pub fn is_secrets_file(path: &str) -> bool {
    let name = Path::new(path)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("");
    let lower = name.to_lowercase();
    lower.starts_with(".env")
        || lower.ends_with(".pem")
        || lower.ends_with(".key")
        || lower.starts_with("id_rsa")
        || lower.starts_with("id_ed25519")
        || lower.ends_with(".p12")
        || lower.ends_with(".pfx")
        || lower == ".npmrc"
        || lower == ".pypirc"
        || lower.starts_with("credentials")
        || lower.starts_with("secrets")
        || path.contains("/secrets/")
}

pub fn is_ci_config(path: &str) -> bool {
    path.starts_with(".github/workflows/")
        || path == ".gitlab-ci.yml"
        || path.starts_with(".circleci/")
        || path == "Jenkinsfile"
        || path == ".travis.yml"
        || path == "bitbucket-pipelines.yml"
        || path == "azure-pipelines.yml"
        || path == "cloudbuild.yaml"
        || path == "appveyor.yml"
}

pub fn is_infra_file(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.ends_with(".tf")
        || lower.ends_with(".tfvars")
        || lower.starts_with("dockerfile")
        || lower.ends_with("/dockerfile")
        || lower == "dockerfile"
        || lower.contains("docker-compose")
        || lower.starts_with("helm/")
        || lower.contains("/helm/")
        || lower.starts_with("k8s/")
        || lower.contains("/kubernetes/")
        || lower.starts_with("pulumi.")
        || lower.starts_with("ansible/")
}

pub fn is_dependency_manifest(path: &str) -> bool {
    let name = Path::new(path)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("");
    matches!(
        name,
        "package.json"
            | "Cargo.toml"
            | "requirements.txt"
            | "go.mod"
            | "Gemfile"
            | "pyproject.toml"
            | "composer.json"
            | "pubspec.yaml"
            | "build.gradle"
            | "build.gradle.kts"
            | "Podfile"
            | "mix.exs"
    )
}

pub fn is_migration_file(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/migrations/")
        || lower.starts_with("migrations/")
        || lower.contains("/migration/")
        || lower.ends_with(".sql")
        || lower.ends_with("prisma/schema.prisma")
        || lower.contains("/alembic/versions/")
}

pub fn is_test_file(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/test/")
        || lower.contains("/tests/")
        || lower.contains("__tests__")
        || lower.contains(".test.")
        || lower.contains(".spec.")
        || lower.contains("_test.")
        || lower.ends_with("_test.go")
        || lower.ends_with(".tests.cs")
}

pub fn is_content_file(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.ends_with(".md")
        || lower.ends_with(".mdx")
        || lower.ends_with(".rst")
        || lower.ends_with(".txt")
        || lower.starts_with("docs/")
        || lower.contains("/docs/")
        || lower.starts_with("content/")
        || lower.contains("/content/")
        || lower.starts_with("copy/")
}

pub fn is_lock_or_generated(path: &str) -> bool {
    let name = Path::new(path)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("");
    matches!(
        name,
        "package-lock.json"
            | "yarn.lock"
            | "pnpm-lock.yaml"
            | "Cargo.lock"
            | "Gemfile.lock"
            | "poetry.lock"
            | "composer.lock"
    )
}

pub fn is_k8s_yaml(path: &str, content: &str) -> bool {
    if !path.ends_with(".yaml") && !path.ends_with(".yml") {
        return false;
    }
    content.contains("apiVersion:") && content.contains("kind:")
}
