import type * as monaco from "monaco-editor";
import type { Theme } from "../stores/uiStore";

const darkDiffColors = {
  "diffEditor.insertedTextBackground": "#2ea04366",
  "diffEditor.removedTextBackground": "#f8514966",
  "diffEditor.insertedLineBackground": "#2ea04340",
  "diffEditor.removedLineBackground": "#f8514940",
  "diffEditorGutter.insertedLineBackground": "#2ea04350",
  "diffEditorGutter.removedLineBackground": "#f8514950",
  "diffEditor.diagonalFill": "#2d333b55",
};

const lightDiffColors = {
  "diffEditor.insertedTextBackground": "#2ea04355",
  "diffEditor.removedTextBackground": "#f8514955",
  "diffEditor.insertedLineBackground": "#2ea04330",
  "diffEditor.removedLineBackground": "#f8514930",
  "diffEditorGutter.insertedLineBackground": "#2ea04340",
  "diffEditorGutter.removedLineBackground": "#f8514940",
  "diffEditor.diagonalFill": "#d0d7de55",
};

export const monacoThemes: Record<Theme, monaco.editor.IStandaloneThemeData> = {
  midnight: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6e7681", fontStyle: "italic" },
      { token: "keyword", foreground: "ff7b72" },
      { token: "string", foreground: "a5d6ff" },
      { token: "number", foreground: "79c0ff" },
      { token: "type", foreground: "ffa657" },
      { token: "function", foreground: "d2a8ff" },
      { token: "variable", foreground: "ffa657" },
      { token: "constant", foreground: "79c0ff" },
      { token: "operator", foreground: "ff7b72" },
      { token: "delimiter", foreground: "8b949e" },
    ],
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#e6edf3",
      "editor.lineHighlightBackground": "#161b2233",
      "editor.selectionBackground": "#264f7844",
      "editor.inactiveSelectionBackground": "#264f7822",
      "editorCursor.foreground": "#3b82f6",
      "editorLineNumber.foreground": "#6e7681",
      "editorLineNumber.activeForeground": "#e6edf3",
      "editorIndentGuide.background": "#21262d",
      "editorIndentGuide.activeBackground": "#30363d",
      "editorWhitespace.foreground": "#21262d",
      "editor.selectionHighlightBackground": "#264f7833",
      "editorBracketMatch.background": "#264f7844",
      "editorBracketMatch.border": "#3b82f644",
      "scrollbarSlider.background": "#2d333b55",
      "scrollbarSlider.hoverBackground": "#373e4788",
      "scrollbarSlider.activeBackground": "#373e47bb",
      "editorWidget.background": "#161b22",
      "editorWidget.border": "#30363d",
      "editorSuggestWidget.background": "#161b22",
      "editorSuggestWidget.border": "#30363d",
      "editorSuggestWidget.selectedBackground": "#2d333b",
      "editorHoverWidget.background": "#161b22",
      "editorHoverWidget.border": "#30363d",
      "minimap.background": "#0d1117",
      ...darkDiffColors,
    },
  },

  graphite: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "8e8e93", fontStyle: "italic" },
      { token: "keyword", foreground: "ff453a" },
      { token: "string", foreground: "30d158" },
      { token: "number", foreground: "64d2ff" },
      { token: "type", foreground: "ffd60a" },
      { token: "function", foreground: "bf5af2" },
      { token: "variable", foreground: "f0883e" },
      { token: "constant", foreground: "64d2ff" },
      { token: "operator", foreground: "ff453a" },
      { token: "delimiter", foreground: "a1a1a6" },
    ],
    colors: {
      "editor.background": "#1c1c1e",
      "editor.foreground": "#f5f5f7",
      "editor.lineHighlightBackground": "#2c2c2e55",
      "editor.selectionBackground": "#f0883e33",
      "editor.inactiveSelectionBackground": "#f0883e18",
      "editorCursor.foreground": "#f0883e",
      "editorLineNumber.foreground": "#8e8e93",
      "editorLineNumber.activeForeground": "#f5f5f7",
      "editorIndentGuide.background": "#2c2c2e",
      "editorIndentGuide.activeBackground": "#3a3a3c",
      "editorWhitespace.foreground": "#2c2c2e",
      "editor.selectionHighlightBackground": "#f0883e22",
      "editorBracketMatch.background": "#f0883e33",
      "editorBracketMatch.border": "#f0883e44",
      "scrollbarSlider.background": "#3a3a3c55",
      "scrollbarSlider.hoverBackground": "#48484a88",
      "scrollbarSlider.activeBackground": "#48484abb",
      "editorWidget.background": "#2c2c2e",
      "editorWidget.border": "#3a3a3c",
      "editorSuggestWidget.background": "#2c2c2e",
      "editorSuggestWidget.border": "#3a3a3c",
      "editorSuggestWidget.selectedBackground": "#3a3a3c",
      "editorHoverWidget.background": "#2c2c2e",
      "editorHoverWidget.border": "#3a3a3c",
      "minimap.background": "#1c1c1e",
      ...darkDiffColors,
    },
  },

  dawn: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6a737d", fontStyle: "italic" },
      { token: "keyword", foreground: "cf222e" },
      { token: "string", foreground: "0a3069" },
      { token: "number", foreground: "0550ae" },
      { token: "type", foreground: "953800" },
      { token: "function", foreground: "8250df" },
      { token: "variable", foreground: "953800" },
      { token: "constant", foreground: "0550ae" },
      { token: "operator", foreground: "cf222e" },
      { token: "delimiter", foreground: "656d76" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#1f2328",
      "editor.lineHighlightBackground": "#f6f8fa",
      "editor.selectionBackground": "#0066cc33",
      "editor.inactiveSelectionBackground": "#0066cc18",
      "editorCursor.foreground": "#0066cc",
      "editorLineNumber.foreground": "#8b949e",
      "editorLineNumber.activeForeground": "#1f2328",
      "editorIndentGuide.background": "#d8dee4",
      "editorIndentGuide.activeBackground": "#d0d7de",
      "editorWhitespace.foreground": "#d8dee4",
      "editor.selectionHighlightBackground": "#0066cc22",
      "editorBracketMatch.background": "#0066cc22",
      "editorBracketMatch.border": "#0066cc44",
      "scrollbarSlider.background": "#d0d7de55",
      "scrollbarSlider.hoverBackground": "#bbc0c688",
      "scrollbarSlider.activeBackground": "#bbc0c6bb",
      "editorWidget.background": "#ffffff",
      "editorWidget.border": "#d0d7de",
      "editorSuggestWidget.background": "#ffffff",
      "editorSuggestWidget.border": "#d0d7de",
      "editorSuggestWidget.selectedBackground": "#eaeef2",
      "editorHoverWidget.background": "#ffffff",
      "editorHoverWidget.border": "#d0d7de",
      "minimap.background": "#ffffff",
      ...lightDiffColors,
    },
  },

  arctic: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "94a3b8", fontStyle: "italic" },
      { token: "keyword", foreground: "dc2626" },
      { token: "string", foreground: "059669" },
      { token: "number", foreground: "0284c7" },
      { token: "type", foreground: "d97706" },
      { token: "function", foreground: "7c3aed" },
      { token: "variable", foreground: "ea580c" },
      { token: "constant", foreground: "0284c7" },
      { token: "operator", foreground: "dc2626" },
      { token: "delimiter", foreground: "475569" },
    ],
    colors: {
      "editor.background": "#f0f4f8",
      "editor.foreground": "#0f172a",
      "editor.lineHighlightBackground": "#e2e8f0",
      "editor.selectionBackground": "#0284c733",
      "editor.inactiveSelectionBackground": "#0284c718",
      "editorCursor.foreground": "#0284c7",
      "editorLineNumber.foreground": "#94a3b8",
      "editorLineNumber.activeForeground": "#0f172a",
      "editorIndentGuide.background": "#e2e8f0",
      "editorIndentGuide.activeBackground": "#cbd5e1",
      "editorWhitespace.foreground": "#e2e8f0",
      "editor.selectionHighlightBackground": "#0284c722",
      "editorBracketMatch.background": "#0284c722",
      "editorBracketMatch.border": "#0284c744",
      "scrollbarSlider.background": "#cbd5e155",
      "scrollbarSlider.hoverBackground": "#94a3b888",
      "scrollbarSlider.activeBackground": "#94a3b8bb",
      "editorWidget.background": "#f8fafc",
      "editorWidget.border": "#cbd5e1",
      "editorSuggestWidget.background": "#f8fafc",
      "editorSuggestWidget.border": "#cbd5e1",
      "editorSuggestWidget.selectedBackground": "#e2e8f0",
      "editorHoverWidget.background": "#f8fafc",
      "editorHoverWidget.border": "#cbd5e1",
      "minimap.background": "#f0f4f8",
      ...lightDiffColors,
    },
  },

  dusk: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "7c6ba0", fontStyle: "italic" },
      { token: "keyword", foreground: "fb7185" },
      { token: "string", foreground: "34d399" },
      { token: "number", foreground: "818cf8" },
      { token: "type", foreground: "fbbf24" },
      { token: "function", foreground: "c084fc" },
      { token: "variable", foreground: "fb923c" },
      { token: "constant", foreground: "818cf8" },
      { token: "operator", foreground: "fb7185" },
      { token: "delimiter", foreground: "a78bfa" },
    ],
    colors: {
      "editor.background": "#1a1625",
      "editor.foreground": "#ede9fe",
      "editor.lineHighlightBackground": "#231e3055",
      "editor.selectionBackground": "#a855f733",
      "editor.inactiveSelectionBackground": "#a855f718",
      "editorCursor.foreground": "#a855f7",
      "editorLineNumber.foreground": "#7c6ba0",
      "editorLineNumber.activeForeground": "#ede9fe",
      "editorIndentGuide.background": "#231e30",
      "editorIndentGuide.activeBackground": "#2d263c",
      "editorWhitespace.foreground": "#231e30",
      "editor.selectionHighlightBackground": "#a855f722",
      "editorBracketMatch.background": "#a855f733",
      "editorBracketMatch.border": "#a855f744",
      "scrollbarSlider.background": "#2d263c55",
      "scrollbarSlider.hoverBackground": "#372f4888",
      "scrollbarSlider.activeBackground": "#372f48bb",
      "editorWidget.background": "#231e30",
      "editorWidget.border": "#2d263c",
      "editorSuggestWidget.background": "#231e30",
      "editorSuggestWidget.border": "#2d263c",
      "editorSuggestWidget.selectedBackground": "#2d263c",
      "editorHoverWidget.background": "#231e30",
      "editorHoverWidget.border": "#2d263c",
      "minimap.background": "#1a1625",
      ...darkDiffColors,
    },
  },

  cyberpunk: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6b4d8a", fontStyle: "italic" },
      { token: "keyword", foreground: "ff0090" },
      { token: "string", foreground: "00ff9f" },
      { token: "number", foreground: "00f5ff" },
      { token: "type", foreground: "ffb800" },
      { token: "function", foreground: "ff00ff" },
      { token: "variable", foreground: "00b4d8" },
      { token: "constant", foreground: "00f5ff" },
      { token: "operator", foreground: "ff0090" },
      { token: "delimiter", foreground: "a080d0" },
    ],
    colors: {
      "editor.background": "#0d0015",
      "editor.foreground": "#e0d0ff",
      "editor.lineHighlightBackground": "#15002555",
      "editor.selectionBackground": "#ff009033",
      "editor.inactiveSelectionBackground": "#ff009018",
      "editorCursor.foreground": "#ff0090",
      "editorLineNumber.foreground": "#6b4d8a",
      "editorLineNumber.activeForeground": "#e0d0ff",
      "editorIndentGuide.background": "#1e0035",
      "editorIndentGuide.activeBackground": "#2a0050",
      "editorWhitespace.foreground": "#1e0035",
      "editor.selectionHighlightBackground": "#ff009022",
      "editorBracketMatch.background": "#ff009033",
      "editorBracketMatch.border": "#ff009044",
      "scrollbarSlider.background": "#2a005055",
      "scrollbarSlider.hoverBackground": "#3d006688",
      "scrollbarSlider.activeBackground": "#3d0066bb",
      "editorWidget.background": "#150025",
      "editorWidget.border": "#2a0050",
      "editorSuggestWidget.background": "#150025",
      "editorSuggestWidget.border": "#2a0050",
      "editorSuggestWidget.selectedBackground": "#2a0050",
      "editorHoverWidget.background": "#150025",
      "editorHoverWidget.border": "#2a0050",
      "minimap.background": "#0d0015",
      ...darkDiffColors,
    },
  },

  ember: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "8a7060", fontStyle: "italic" },
      { token: "keyword", foreground: "ef4444" },
      { token: "string", foreground: "84cc16" },
      { token: "number", foreground: "60a5fa" },
      { token: "type", foreground: "f97316" },
      { token: "function", foreground: "e879f9" },
      { token: "variable", foreground: "fb923c" },
      { token: "constant", foreground: "60a5fa" },
      { token: "operator", foreground: "ef4444" },
      { token: "delimiter", foreground: "c0a090" },
    ],
    colors: {
      "editor.background": "#1a1210",
      "editor.foreground": "#f0e0d6",
      "editor.lineHighlightBackground": "#241a1655",
      "editor.selectionBackground": "#f9731633",
      "editor.inactiveSelectionBackground": "#f9731618",
      "editorCursor.foreground": "#f97316",
      "editorLineNumber.foreground": "#8a7060",
      "editorLineNumber.activeForeground": "#f0e0d6",
      "editorIndentGuide.background": "#2e221c",
      "editorIndentGuide.activeBackground": "#3a2c24",
      "editorWhitespace.foreground": "#2e221c",
      "editor.selectionHighlightBackground": "#f9731622",
      "editorBracketMatch.background": "#f9731633",
      "editorBracketMatch.border": "#f9731644",
      "scrollbarSlider.background": "#3a2c2455",
      "scrollbarSlider.hoverBackground": "#4a3c3488",
      "scrollbarSlider.activeBackground": "#4a3c34bb",
      "editorWidget.background": "#241a16",
      "editorWidget.border": "#3a2c24",
      "editorSuggestWidget.background": "#241a16",
      "editorSuggestWidget.border": "#3a2c24",
      "editorSuggestWidget.selectedBackground": "#3a2c24",
      "editorHoverWidget.background": "#241a16",
      "editorHoverWidget.border": "#3a2c24",
      "minimap.background": "#1a1210",
      ...darkDiffColors,
    },
  },

  forest: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "5c7a54", fontStyle: "italic" },
      { token: "keyword", foreground: "ef4444" },
      { token: "string", foreground: "22c55e" },
      { token: "number", foreground: "38bdf8" },
      { token: "type", foreground: "eab308" },
      { token: "function", foreground: "c084fc" },
      { token: "variable", foreground: "4ade80" },
      { token: "constant", foreground: "38bdf8" },
      { token: "operator", foreground: "ef4444" },
      { token: "delimiter", foreground: "90b888" },
    ],
    colors: {
      "editor.background": "#0f1a0f",
      "editor.foreground": "#d4e8d0",
      "editor.lineHighlightBackground": "#16241655",
      "editor.selectionBackground": "#22c55e33",
      "editor.inactiveSelectionBackground": "#22c55e18",
      "editorCursor.foreground": "#22c55e",
      "editorLineNumber.foreground": "#5c7a54",
      "editorLineNumber.activeForeground": "#d4e8d0",
      "editorIndentGuide.background": "#1e2e1e",
      "editorIndentGuide.activeBackground": "#283a28",
      "editorWhitespace.foreground": "#1e2e1e",
      "editor.selectionHighlightBackground": "#22c55e22",
      "editorBracketMatch.background": "#22c55e33",
      "editorBracketMatch.border": "#22c55e44",
      "scrollbarSlider.background": "#283a2855",
      "scrollbarSlider.hoverBackground": "#3a4c3a88",
      "scrollbarSlider.activeBackground": "#3a4c3abb",
      "editorWidget.background": "#162416",
      "editorWidget.border": "#283a28",
      "editorSuggestWidget.background": "#162416",
      "editorSuggestWidget.border": "#283a28",
      "editorSuggestWidget.selectedBackground": "#283a28",
      "editorHoverWidget.background": "#162416",
      "editorHoverWidget.border": "#283a28",
      "minimap.background": "#0f1a0f",
      ...darkDiffColors,
    },
  },

  "solarized-dark": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "586e75", fontStyle: "italic" },
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2aa198" },
      { token: "number", foreground: "d33682" },
      { token: "type", foreground: "b58900" },
      { token: "function", foreground: "268bd2" },
      { token: "variable", foreground: "cb4b16" },
      { token: "constant", foreground: "d33682" },
      { token: "operator", foreground: "859900" },
      { token: "delimiter", foreground: "657b83" },
    ],
    colors: {
      "editor.background": "#002b36",
      "editor.foreground": "#839496",
      "editor.lineHighlightBackground": "#07364255",
      "editor.selectionBackground": "#268bd233",
      "editor.inactiveSelectionBackground": "#268bd218",
      "editorCursor.foreground": "#268bd2",
      "editorLineNumber.foreground": "#586e75",
      "editorLineNumber.activeForeground": "#93a1a1",
      "editorIndentGuide.background": "#073642",
      "editorIndentGuide.activeBackground": "#0a4050",
      "editorWhitespace.foreground": "#073642",
      "editor.selectionHighlightBackground": "#268bd222",
      "editorBracketMatch.background": "#268bd233",
      "editorBracketMatch.border": "#268bd244",
      "scrollbarSlider.background": "#0a405055",
      "scrollbarSlider.hoverBackground": "#10505e88",
      "scrollbarSlider.activeBackground": "#10505ebb",
      "editorWidget.background": "#073642",
      "editorWidget.border": "#0a4050",
      "editorSuggestWidget.background": "#073642",
      "editorSuggestWidget.border": "#0a4050",
      "editorSuggestWidget.selectedBackground": "#0a4050",
      "editorHoverWidget.background": "#073642",
      "editorHoverWidget.border": "#0a4050",
      "minimap.background": "#002b36",
      ...darkDiffColors,
    },
  },

  monokai: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "75715e", fontStyle: "italic" },
      { token: "keyword", foreground: "f92672" },
      { token: "string", foreground: "e6db74" },
      { token: "number", foreground: "ae81ff" },
      { token: "type", foreground: "66d9ef" },
      { token: "function", foreground: "a6e22e" },
      { token: "variable", foreground: "fd971f" },
      { token: "constant", foreground: "ae81ff" },
      { token: "operator", foreground: "f92672" },
      { token: "delimiter", foreground: "a6a69a" },
    ],
    colors: {
      "editor.background": "#272822",
      "editor.foreground": "#f8f8f2",
      "editor.lineHighlightBackground": "#2f302a55",
      "editor.selectionBackground": "#a6e22e25",
      "editor.inactiveSelectionBackground": "#a6e22e12",
      "editorCursor.foreground": "#a6e22e",
      "editorLineNumber.foreground": "#75715e",
      "editorLineNumber.activeForeground": "#f8f8f2",
      "editorIndentGuide.background": "#3b3c35",
      "editorIndentGuide.activeBackground": "#49483e",
      "editorWhitespace.foreground": "#3b3c35",
      "editor.selectionHighlightBackground": "#a6e22e18",
      "editorBracketMatch.background": "#a6e22e33",
      "editorBracketMatch.border": "#a6e22e44",
      "scrollbarSlider.background": "#49483e55",
      "scrollbarSlider.hoverBackground": "#5a594e88",
      "scrollbarSlider.activeBackground": "#5a594ebb",
      "editorWidget.background": "#2f302a",
      "editorWidget.border": "#49483e",
      "editorSuggestWidget.background": "#2f302a",
      "editorSuggestWidget.border": "#49483e",
      "editorSuggestWidget.selectedBackground": "#49483e",
      "editorHoverWidget.background": "#2f302a",
      "editorHoverWidget.border": "#49483e",
      "minimap.background": "#272822",
      ...darkDiffColors,
    },
  },

  nord: {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "616e88", fontStyle: "italic" },
      { token: "keyword", foreground: "81a1c1" },
      { token: "string", foreground: "a3be8c" },
      { token: "number", foreground: "b48ead" },
      { token: "type", foreground: "8fbcbb" },
      { token: "function", foreground: "88c0d0" },
      { token: "variable", foreground: "d8dee9" },
      { token: "constant", foreground: "b48ead" },
      { token: "operator", foreground: "81a1c1" },
      { token: "delimiter", foreground: "d8dee9" },
    ],
    colors: {
      "editor.background": "#2e3440", "editor.foreground": "#d8dee9",
      "editor.lineHighlightBackground": "#3b425255", "editor.selectionBackground": "#88c0d033",
      "editor.inactiveSelectionBackground": "#88c0d018", "editorCursor.foreground": "#88c0d0",
      "editorLineNumber.foreground": "#616e88", "editorLineNumber.activeForeground": "#d8dee9",
      "editorIndentGuide.background": "#3b4252", "editorIndentGuide.activeBackground": "#434c5e",
      "editorWhitespace.foreground": "#3b4252", "editor.selectionHighlightBackground": "#88c0d022",
      "editorBracketMatch.background": "#88c0d033", "editorBracketMatch.border": "#88c0d044",
      "scrollbarSlider.background": "#434c5e55", "scrollbarSlider.hoverBackground": "#4c566a88",
      "scrollbarSlider.activeBackground": "#4c566abb",
      "editorWidget.background": "#3b4252", "editorWidget.border": "#434c5e",
      "editorSuggestWidget.background": "#3b4252", "editorSuggestWidget.border": "#434c5e",
      "editorSuggestWidget.selectedBackground": "#434c5e",
      "editorHoverWidget.background": "#3b4252", "editorHoverWidget.border": "#434c5e",
      "minimap.background": "#2e3440", ...darkDiffColors,
    },
  },

  dracula: {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "6272a4", fontStyle: "italic" },
      { token: "keyword", foreground: "ff79c6" },
      { token: "string", foreground: "f1fa8c" },
      { token: "number", foreground: "bd93f9" },
      { token: "type", foreground: "8be9fd" },
      { token: "function", foreground: "50fa7b" },
      { token: "variable", foreground: "f8f8f2" },
      { token: "constant", foreground: "bd93f9" },
      { token: "operator", foreground: "ff79c6" },
      { token: "delimiter", foreground: "f8f8f2" },
    ],
    colors: {
      "editor.background": "#282a36", "editor.foreground": "#f8f8f2",
      "editor.lineHighlightBackground": "#2d2f3d55", "editor.selectionBackground": "#bd93f933",
      "editor.inactiveSelectionBackground": "#bd93f918", "editorCursor.foreground": "#bd93f9",
      "editorLineNumber.foreground": "#6272a4", "editorLineNumber.activeForeground": "#f8f8f2",
      "editorIndentGuide.background": "#343746", "editorIndentGuide.activeBackground": "#44475a",
      "editorWhitespace.foreground": "#343746", "editor.selectionHighlightBackground": "#bd93f922",
      "editorBracketMatch.background": "#bd93f933", "editorBracketMatch.border": "#bd93f944",
      "scrollbarSlider.background": "#44475a55", "scrollbarSlider.hoverBackground": "#4c4f6888",
      "scrollbarSlider.activeBackground": "#4c4f68bb",
      "editorWidget.background": "#2d2f3d", "editorWidget.border": "#44475a",
      "editorSuggestWidget.background": "#2d2f3d", "editorSuggestWidget.border": "#44475a",
      "editorSuggestWidget.selectedBackground": "#44475a",
      "editorHoverWidget.background": "#2d2f3d", "editorHoverWidget.border": "#44475a",
      "minimap.background": "#282a36", ...darkDiffColors,
    },
  },

  "one-dark": {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "5c6370", fontStyle: "italic" },
      { token: "keyword", foreground: "c678dd" },
      { token: "string", foreground: "98c379" },
      { token: "number", foreground: "d19a66" },
      { token: "type", foreground: "e5c07b" },
      { token: "function", foreground: "61afef" },
      { token: "variable", foreground: "e06c75" },
      { token: "constant", foreground: "d19a66" },
      { token: "operator", foreground: "56b6c2" },
      { token: "delimiter", foreground: "abb2bf" },
    ],
    colors: {
      "editor.background": "#282c34", "editor.foreground": "#abb2bf",
      "editor.lineHighlightBackground": "#2c313a55", "editor.selectionBackground": "#61afef33",
      "editor.inactiveSelectionBackground": "#61afef18", "editorCursor.foreground": "#61afef",
      "editorLineNumber.foreground": "#5c6370", "editorLineNumber.activeForeground": "#abb2bf",
      "editorIndentGuide.background": "#333842", "editorIndentGuide.activeBackground": "#3e4451",
      "editorWhitespace.foreground": "#333842", "editor.selectionHighlightBackground": "#61afef22",
      "editorBracketMatch.background": "#61afef33", "editorBracketMatch.border": "#61afef44",
      "scrollbarSlider.background": "#3e445155", "scrollbarSlider.hoverBackground": "#4b515e88",
      "scrollbarSlider.activeBackground": "#4b515ebb",
      "editorWidget.background": "#2c313a", "editorWidget.border": "#3e4451",
      "editorSuggestWidget.background": "#2c313a", "editorSuggestWidget.border": "#3e4451",
      "editorSuggestWidget.selectedBackground": "#3e4451",
      "editorHoverWidget.background": "#2c313a", "editorHoverWidget.border": "#3e4451",
      "minimap.background": "#282c34", ...darkDiffColors,
    },
  },

  "tokyo-night": {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "565f89", fontStyle: "italic" },
      { token: "keyword", foreground: "bb9af7" },
      { token: "string", foreground: "9ece6a" },
      { token: "number", foreground: "ff9e64" },
      { token: "type", foreground: "2ac3de" },
      { token: "function", foreground: "7aa2f7" },
      { token: "variable", foreground: "c0caf5" },
      { token: "constant", foreground: "ff9e64" },
      { token: "operator", foreground: "89ddff" },
      { token: "delimiter", foreground: "a9b1d6" },
    ],
    colors: {
      "editor.background": "#1a1b26", "editor.foreground": "#c0caf5",
      "editor.lineHighlightBackground": "#1f233555", "editor.selectionBackground": "#7aa2f733",
      "editor.inactiveSelectionBackground": "#7aa2f718", "editorCursor.foreground": "#7aa2f7",
      "editorLineNumber.foreground": "#565f89", "editorLineNumber.activeForeground": "#c0caf5",
      "editorIndentGuide.background": "#1f2335", "editorIndentGuide.activeBackground": "#292e42",
      "editorWhitespace.foreground": "#1f2335", "editor.selectionHighlightBackground": "#7aa2f722",
      "editorBracketMatch.background": "#7aa2f733", "editorBracketMatch.border": "#7aa2f744",
      "scrollbarSlider.background": "#292e4255", "scrollbarSlider.hoverBackground": "#33384d88",
      "scrollbarSlider.activeBackground": "#33384dbb",
      "editorWidget.background": "#1f2335", "editorWidget.border": "#292e42",
      "editorSuggestWidget.background": "#1f2335", "editorSuggestWidget.border": "#292e42",
      "editorSuggestWidget.selectedBackground": "#292e42",
      "editorHoverWidget.background": "#1f2335", "editorHoverWidget.border": "#292e42",
      "minimap.background": "#1a1b26", ...darkDiffColors,
    },
  },

  catppuccin: {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "6c7086", fontStyle: "italic" },
      { token: "keyword", foreground: "cba6f7" },
      { token: "string", foreground: "a6e3a1" },
      { token: "number", foreground: "fab387" },
      { token: "type", foreground: "89b4fa" },
      { token: "function", foreground: "89b4fa" },
      { token: "variable", foreground: "cdd6f4" },
      { token: "constant", foreground: "fab387" },
      { token: "operator", foreground: "89dceb" },
      { token: "delimiter", foreground: "bac2de" },
    ],
    colors: {
      "editor.background": "#1e1e2e", "editor.foreground": "#cdd6f4",
      "editor.lineHighlightBackground": "#24243e55", "editor.selectionBackground": "#cba6f733",
      "editor.inactiveSelectionBackground": "#cba6f718", "editorCursor.foreground": "#cba6f7",
      "editorLineNumber.foreground": "#6c7086", "editorLineNumber.activeForeground": "#cdd6f4",
      "editorIndentGuide.background": "#24243e", "editorIndentGuide.activeBackground": "#313244",
      "editorWhitespace.foreground": "#24243e", "editor.selectionHighlightBackground": "#cba6f722",
      "editorBracketMatch.background": "#cba6f733", "editorBracketMatch.border": "#cba6f744",
      "scrollbarSlider.background": "#31324455", "scrollbarSlider.hoverBackground": "#3b3d5488",
      "scrollbarSlider.activeBackground": "#3b3d54bb",
      "editorWidget.background": "#24243e", "editorWidget.border": "#313244",
      "editorSuggestWidget.background": "#24243e", "editorSuggestWidget.border": "#313244",
      "editorSuggestWidget.selectedBackground": "#313244",
      "editorHoverWidget.background": "#24243e", "editorHoverWidget.border": "#313244",
      "minimap.background": "#1e1e2e", ...darkDiffColors,
    },
  },

  "rose-pine": {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "6e6a86", fontStyle: "italic" },
      { token: "keyword", foreground: "31748f" },
      { token: "string", foreground: "f6c177" },
      { token: "number", foreground: "ebbcba" },
      { token: "type", foreground: "9ccfd8" },
      { token: "function", foreground: "ebbcba" },
      { token: "variable", foreground: "e0def4" },
      { token: "constant", foreground: "eb6f92" },
      { token: "operator", foreground: "908caa" },
      { token: "delimiter", foreground: "908caa" },
    ],
    colors: {
      "editor.background": "#191724", "editor.foreground": "#e0def4",
      "editor.lineHighlightBackground": "#1f1d2e55", "editor.selectionBackground": "#ebbcba33",
      "editor.inactiveSelectionBackground": "#ebbcba18", "editorCursor.foreground": "#ebbcba",
      "editorLineNumber.foreground": "#6e6a86", "editorLineNumber.activeForeground": "#e0def4",
      "editorIndentGuide.background": "#1f1d2e", "editorIndentGuide.activeBackground": "#26233a",
      "editorWhitespace.foreground": "#1f1d2e", "editor.selectionHighlightBackground": "#ebbcba22",
      "editorBracketMatch.background": "#ebbcba33", "editorBracketMatch.border": "#ebbcba44",
      "scrollbarSlider.background": "#26233a55", "scrollbarSlider.hoverBackground": "#2a274088",
      "scrollbarSlider.activeBackground": "#2a2740bb",
      "editorWidget.background": "#1f1d2e", "editorWidget.border": "#26233a",
      "editorSuggestWidget.background": "#1f1d2e", "editorSuggestWidget.border": "#26233a",
      "editorSuggestWidget.selectedBackground": "#26233a",
      "editorHoverWidget.background": "#1f1d2e", "editorHoverWidget.border": "#26233a",
      "minimap.background": "#191724", ...darkDiffColors,
    },
  },

  "ayu-dark": {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "565b66", fontStyle: "italic" },
      { token: "keyword", foreground: "ff8f40" },
      { token: "string", foreground: "aad94c" },
      { token: "number", foreground: "d2a6ff" },
      { token: "type", foreground: "39bae6" },
      { token: "function", foreground: "ffb454" },
      { token: "variable", foreground: "bfbdb6" },
      { token: "constant", foreground: "d2a6ff" },
      { token: "operator", foreground: "f29668" },
      { token: "delimiter", foreground: "8b8680" },
    ],
    colors: {
      "editor.background": "#0a0e14", "editor.foreground": "#bfbdb6",
      "editor.lineHighlightBackground": "#0d111755", "editor.selectionBackground": "#ffb45433",
      "editor.inactiveSelectionBackground": "#ffb45418", "editorCursor.foreground": "#ffb454",
      "editorLineNumber.foreground": "#565b66", "editorLineNumber.activeForeground": "#bfbdb6",
      "editorIndentGuide.background": "#131721", "editorIndentGuide.activeBackground": "#1a1f2b",
      "editorWhitespace.foreground": "#131721", "editor.selectionHighlightBackground": "#ffb45422",
      "editorBracketMatch.background": "#ffb45433", "editorBracketMatch.border": "#ffb45444",
      "scrollbarSlider.background": "#1a1f2b55", "scrollbarSlider.hoverBackground": "#24293588",
      "scrollbarSlider.activeBackground": "#242935bb",
      "editorWidget.background": "#0d1117", "editorWidget.border": "#1a1f2b",
      "editorSuggestWidget.background": "#0d1117", "editorSuggestWidget.border": "#1a1f2b",
      "editorSuggestWidget.selectedBackground": "#1a1f2b",
      "editorHoverWidget.background": "#0d1117", "editorHoverWidget.border": "#1a1f2b",
      "minimap.background": "#0a0e14", ...darkDiffColors,
    },
  },

  vesper: {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "525252", fontStyle: "italic" },
      { token: "keyword", foreground: "ffc799" },
      { token: "string", foreground: "a8cc8c" },
      { token: "number", foreground: "d4bfff" },
      { token: "type", foreground: "82aaff" },
      { token: "function", foreground: "ffc799" },
      { token: "variable", foreground: "d4d4d4" },
      { token: "constant", foreground: "d4bfff" },
      { token: "operator", foreground: "ffc799" },
      { token: "delimiter", foreground: "a3a3a3" },
    ],
    colors: {
      "editor.background": "#101010", "editor.foreground": "#d4d4d4",
      "editor.lineHighlightBackground": "#18181855", "editor.selectionBackground": "#ffc79933",
      "editor.inactiveSelectionBackground": "#ffc79918", "editorCursor.foreground": "#ffc799",
      "editorLineNumber.foreground": "#525252", "editorLineNumber.activeForeground": "#d4d4d4",
      "editorIndentGuide.background": "#1e1e1e", "editorIndentGuide.activeBackground": "#262626",
      "editorWhitespace.foreground": "#1e1e1e", "editor.selectionHighlightBackground": "#ffc79922",
      "editorBracketMatch.background": "#ffc79933", "editorBracketMatch.border": "#ffc79944",
      "scrollbarSlider.background": "#26262655", "scrollbarSlider.hoverBackground": "#33333388",
      "scrollbarSlider.activeBackground": "#333333bb",
      "editorWidget.background": "#181818", "editorWidget.border": "#262626",
      "editorSuggestWidget.background": "#181818", "editorSuggestWidget.border": "#262626",
      "editorSuggestWidget.selectedBackground": "#262626",
      "editorHoverWidget.background": "#181818", "editorHoverWidget.border": "#262626",
      "minimap.background": "#101010", ...darkDiffColors,
    },
  },

  poimandres: {
    base: "vs-dark", inherit: true,
    rules: [
      { token: "comment", foreground: "506477", fontStyle: "italic" },
      { token: "keyword", foreground: "5de4c7" },
      { token: "string", foreground: "5de4c7" },
      { token: "number", foreground: "d0679d" },
      { token: "type", foreground: "89ddff" },
      { token: "function", foreground: "a6accd" },
      { token: "variable", foreground: "e4f0fb" },
      { token: "constant", foreground: "d0679d" },
      { token: "operator", foreground: "89ddff" },
      { token: "delimiter", foreground: "a6accd" },
    ],
    colors: {
      "editor.background": "#1b1e28", "editor.foreground": "#e4f0fb",
      "editor.lineHighlightBackground": "#1f223355", "editor.selectionBackground": "#a6accd33",
      "editor.inactiveSelectionBackground": "#a6accd18", "editorCursor.foreground": "#a6accd",
      "editorLineNumber.foreground": "#506477", "editorLineNumber.activeForeground": "#e4f0fb",
      "editorIndentGuide.background": "#1f2233", "editorIndentGuide.activeBackground": "#2b3045",
      "editorWhitespace.foreground": "#1f2233", "editor.selectionHighlightBackground": "#a6accd22",
      "editorBracketMatch.background": "#a6accd33", "editorBracketMatch.border": "#a6accd44",
      "scrollbarSlider.background": "#2b304555", "scrollbarSlider.hoverBackground": "#33395088",
      "scrollbarSlider.activeBackground": "#333950bb",
      "editorWidget.background": "#1f2233", "editorWidget.border": "#2b3045",
      "editorSuggestWidget.background": "#1f2233", "editorSuggestWidget.border": "#2b3045",
      "editorSuggestWidget.selectedBackground": "#2b3045",
      "editorHoverWidget.background": "#1f2233", "editorHoverWidget.border": "#2b3045",
      "minimap.background": "#1b1e28", ...darkDiffColors,
    },
  },

  "pale-fire": {
    base: "vs", inherit: true,
    rules: [
      { token: "comment", foreground: "9893a5", fontStyle: "italic" },
      { token: "keyword", foreground: "286983" },
      { token: "string", foreground: "ea9d34" },
      { token: "number", foreground: "b4637a" },
      { token: "type", foreground: "56949f" },
      { token: "function", foreground: "d7827e" },
      { token: "variable", foreground: "575279" },
      { token: "constant", foreground: "b4637a" },
      { token: "operator", foreground: "286983" },
      { token: "delimiter", foreground: "797593" },
    ],
    colors: {
      "editor.background": "#faf4ed", "editor.foreground": "#575279",
      "editor.lineHighlightBackground": "#f2e9de", "editor.selectionBackground": "#b4637a33",
      "editor.inactiveSelectionBackground": "#b4637a18", "editorCursor.foreground": "#b4637a",
      "editorLineNumber.foreground": "#9893a5", "editorLineNumber.activeForeground": "#575279",
      "editorIndentGuide.background": "#f2e9e1", "editorIndentGuide.activeBackground": "#dfdad9",
      "editorWhitespace.foreground": "#f2e9e1", "editor.selectionHighlightBackground": "#b4637a22",
      "editorBracketMatch.background": "#b4637a22", "editorBracketMatch.border": "#b4637a44",
      "scrollbarSlider.background": "#dfdad955", "scrollbarSlider.hoverBackground": "#cecacd88",
      "scrollbarSlider.activeBackground": "#cecacdbb",
      "editorWidget.background": "#fffaf3", "editorWidget.border": "#dfdad9",
      "editorSuggestWidget.background": "#fffaf3", "editorSuggestWidget.border": "#dfdad9",
      "editorSuggestWidget.selectedBackground": "#f2e9de",
      "editorHoverWidget.background": "#fffaf3", "editorHoverWidget.border": "#dfdad9",
      "minimap.background": "#faf4ed", ...lightDiffColors,
    },
  },
};
