import type * as monaco from "monaco-editor";
import type { Theme } from "../stores/uiStore";

export const monacoThemes: Record<Theme, monaco.editor.IStandaloneThemeData> = {
  midnight: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6e7681", fontStyle: "italic" },
      { token: "keyword", foreground: "ff7b72" },
      { token: "string", foreground: "a5d6ff" },
      { token: "number", foreground: "79c0ff" },
      { token: "type", foreground: "ffa657" },
      { token: "function", foreground: "d2a8ff" },
      { token: "variable", foreground: "ffa657" },
      { token: "constant", foreground: "79c0ff" },
      { token: "operator", foreground: "ff7b72" },
      { token: "delimiter", foreground: "8b949e" },
    ],
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#e6edf3",
      "editor.lineHighlightBackground": "#161b2233",
      "editor.selectionBackground": "#264f7844",
      "editor.inactiveSelectionBackground": "#264f7822",
      "editorCursor.foreground": "#3b82f6",
      "editorLineNumber.foreground": "#6e7681",
      "editorLineNumber.activeForeground": "#e6edf3",
      "editorIndentGuide.background": "#21262d",
      "editorIndentGuide.activeBackground": "#30363d",
      "editorWhitespace.foreground": "#21262d",
      "editor.selectionHighlightBackground": "#264f7833",
      "editorBracketMatch.background": "#264f7844",
      "editorBracketMatch.border": "#3b82f644",
      "scrollbarSlider.background": "#2d333b55",
      "scrollbarSlider.hoverBackground": "#373e4788",
      "scrollbarSlider.activeBackground": "#373e47bb",
      "editorWidget.background": "#161b22",
      "editorWidget.border": "#30363d",
      "editorSuggestWidget.background": "#161b22",
      "editorSuggestWidget.border": "#30363d",
      "editorSuggestWidget.selectedBackground": "#2d333b",
      "editorHoverWidget.background": "#161b22",
      "editorHoverWidget.border": "#30363d",
      "minimap.background": "#0d1117",
    },
  },

  graphite: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "8e8e93", fontStyle: "italic" },
      { token: "keyword", foreground: "ff453a" },
      { token: "string", foreground: "30d158" },
      { token: "number", foreground: "64d2ff" },
      { token: "type", foreground: "ffd60a" },
      { token: "function", foreground: "bf5af2" },
      { token: "variable", foreground: "f0883e" },
      { token: "constant", foreground: "64d2ff" },
      { token: "operator", foreground: "ff453a" },
      { token: "delimiter", foreground: "a1a1a6" },
    ],
    colors: {
      "editor.background": "#1c1c1e",
      "editor.foreground": "#f5f5f7",
      "editor.lineHighlightBackground": "#2c2c2e55",
      "editor.selectionBackground": "#f0883e33",
      "editor.inactiveSelectionBackground": "#f0883e18",
      "editorCursor.foreground": "#f0883e",
      "editorLineNumber.foreground": "#8e8e93",
      "editorLineNumber.activeForeground": "#f5f5f7",
      "editorIndentGuide.background": "#2c2c2e",
      "editorIndentGuide.activeBackground": "#3a3a3c",
      "editorWhitespace.foreground": "#2c2c2e",
      "editor.selectionHighlightBackground": "#f0883e22",
      "editorBracketMatch.background": "#f0883e33",
      "editorBracketMatch.border": "#f0883e44",
      "scrollbarSlider.background": "#3a3a3c55",
      "scrollbarSlider.hoverBackground": "#48484a88",
      "scrollbarSlider.activeBackground": "#48484abb",
      "editorWidget.background": "#2c2c2e",
      "editorWidget.border": "#3a3a3c",
      "editorSuggestWidget.background": "#2c2c2e",
      "editorSuggestWidget.border": "#3a3a3c",
      "editorSuggestWidget.selectedBackground": "#3a3a3c",
      "editorHoverWidget.background": "#2c2c2e",
      "editorHoverWidget.border": "#3a3a3c",
      "minimap.background": "#1c1c1e",
    },
  },

  dawn: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6a737d", fontStyle: "italic" },
      { token: "keyword", foreground: "cf222e" },
      { token: "string", foreground: "0a3069" },
      { token: "number", foreground: "0550ae" },
      { token: "type", foreground: "953800" },
      { token: "function", foreground: "8250df" },
      { token: "variable", foreground: "953800" },
      { token: "constant", foreground: "0550ae" },
      { token: "operator", foreground: "cf222e" },
      { token: "delimiter", foreground: "656d76" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#1f2328",
      "editor.lineHighlightBackground": "#f6f8fa",
      "editor.selectionBackground": "#0066cc33",
      "editor.inactiveSelectionBackground": "#0066cc18",
      "editorCursor.foreground": "#0066cc",
      "editorLineNumber.foreground": "#8b949e",
      "editorLineNumber.activeForeground": "#1f2328",
      "editorIndentGuide.background": "#d8dee4",
      "editorIndentGuide.activeBackground": "#d0d7de",
      "editorWhitespace.foreground": "#d8dee4",
      "editor.selectionHighlightBackground": "#0066cc22",
      "editorBracketMatch.background": "#0066cc22",
      "editorBracketMatch.border": "#0066cc44",
      "scrollbarSlider.background": "#d0d7de55",
      "scrollbarSlider.hoverBackground": "#bbc0c688",
      "scrollbarSlider.activeBackground": "#bbc0c6bb",
      "editorWidget.background": "#ffffff",
      "editorWidget.border": "#d0d7de",
      "editorSuggestWidget.background": "#ffffff",
      "editorSuggestWidget.border": "#d0d7de",
      "editorSuggestWidget.selectedBackground": "#eaeef2",
      "editorHoverWidget.background": "#ffffff",
      "editorHoverWidget.border": "#d0d7de",
      "minimap.background": "#ffffff",
    },
  },

  arctic: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "94a3b8", fontStyle: "italic" },
      { token: "keyword", foreground: "dc2626" },
      { token: "string", foreground: "059669" },
      { token: "number", foreground: "0284c7" },
      { token: "type", foreground: "d97706" },
      { token: "function", foreground: "7c3aed" },
      { token: "variable", foreground: "ea580c" },
      { token: "constant", foreground: "0284c7" },
      { token: "operator", foreground: "dc2626" },
      { token: "delimiter", foreground: "475569" },
    ],
    colors: {
      "editor.background": "#f0f4f8",
      "editor.foreground": "#0f172a",
      "editor.lineHighlightBackground": "#e2e8f0",
      "editor.selectionBackground": "#0284c733",
      "editor.inactiveSelectionBackground": "#0284c718",
      "editorCursor.foreground": "#0284c7",
      "editorLineNumber.foreground": "#94a3b8",
      "editorLineNumber.activeForeground": "#0f172a",
      "editorIndentGuide.background": "#e2e8f0",
      "editorIndentGuide.activeBackground": "#cbd5e1",
      "editorWhitespace.foreground": "#e2e8f0",
      "editor.selectionHighlightBackground": "#0284c722",
      "editorBracketMatch.background": "#0284c722",
      "editorBracketMatch.border": "#0284c744",
      "scrollbarSlider.background": "#cbd5e155",
      "scrollbarSlider.hoverBackground": "#94a3b888",
      "scrollbarSlider.activeBackground": "#94a3b8bb",
      "editorWidget.background": "#f8fafc",
      "editorWidget.border": "#cbd5e1",
      "editorSuggestWidget.background": "#f8fafc",
      "editorSuggestWidget.border": "#cbd5e1",
      "editorSuggestWidget.selectedBackground": "#e2e8f0",
      "editorHoverWidget.background": "#f8fafc",
      "editorHoverWidget.border": "#cbd5e1",
      "minimap.background": "#f0f4f8",
    },
  },

  dusk: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "7c6ba0", fontStyle: "italic" },
      { token: "keyword", foreground: "fb7185" },
      { token: "string", foreground: "34d399" },
      { token: "number", foreground: "818cf8" },
      { token: "type", foreground: "fbbf24" },
      { token: "function", foreground: "c084fc" },
      { token: "variable", foreground: "fb923c" },
      { token: "constant", foreground: "818cf8" },
      { token: "operator", foreground: "fb7185" },
      { token: "delimiter", foreground: "a78bfa" },
    ],
    colors: {
      "editor.background": "#1a1625",
      "editor.foreground": "#ede9fe",
      "editor.lineHighlightBackground": "#231e3055",
      "editor.selectionBackground": "#a855f733",
      "editor.inactiveSelectionBackground": "#a855f718",
      "editorCursor.foreground": "#a855f7",
      "editorLineNumber.foreground": "#7c6ba0",
      "editorLineNumber.activeForeground": "#ede9fe",
      "editorIndentGuide.background": "#231e30",
      "editorIndentGuide.activeBackground": "#2d263c",
      "editorWhitespace.foreground": "#231e30",
      "editor.selectionHighlightBackground": "#a855f722",
      "editorBracketMatch.background": "#a855f733",
      "editorBracketMatch.border": "#a855f744",
      "scrollbarSlider.background": "#2d263c55",
      "scrollbarSlider.hoverBackground": "#372f4888",
      "scrollbarSlider.activeBackground": "#372f48bb",
      "editorWidget.background": "#231e30",
      "editorWidget.border": "#2d263c",
      "editorSuggestWidget.background": "#231e30",
      "editorSuggestWidget.border": "#2d263c",
      "editorSuggestWidget.selectedBackground": "#2d263c",
      "editorHoverWidget.background": "#231e30",
      "editorHoverWidget.border": "#2d263c",
      "minimap.background": "#1a1625",
    },
  },
};
